### ISSUE TITLE
Runtime Error 339

### ISSUE THREAD

**Issue by AllanKustom** [Hawke/B17QoTS#1]
I have downloaded all of the files as a zip and unzipped them to a folder. 
Then I go to the folder "B17QotSEmulator" and click the "B17QotSEmulator.exe" the splash screen appears and I get the error message
Runtime Error 339
Component "COMDLG32OCX" or one of its dependencies not correctly registered a file is missing or invalid.

Any help most gratefully received!
Thanks
![b17](https://cloud.githubusercontent.com/assets/26148191/23523780/2065768c-ff80-11e6-82a3-a0fd8b5930c6.jpg)

**Comment by Hawke** [comment]
It's not really intended to be run directly from the source tree like that (the .exe probably shouldn't even be included there). Normally COMDLG32.OCX is loaded and registered when you install the software. As such I would recommend grabbing the installer from https://github.com/Hawke/B17QoTS/tree/master/current_public_distro and installing/running it that way.

Hope this helps.

**Comment by AllanKustom** [comment]
Awesome thank you very much. 
All sorted time to fly some bomber sorties!
